
package dev.imrob.appvendas.gui.vendas.modal;

import dev.imrob.appvendas.entity.Cliente;
import dev.imrob.appvendas.service.ClienteService;
import javax.swing.JTextField;

/**
 *
 * @author Rob
 */
public class InserirCliente extends javax.swing.JPanel {
    private final String CUPOM_DESCONTO_5 = "PRIMEIRACOMPRA";
    private final String CUPOM_DESCONTO_10 = "QUERO10";
    
    public InserirCliente() {
        initComponents();   
    }
    
    public Cliente getCliente() {
        Cliente cliente = new Cliente();
        Long id = Long.valueOf(txtIdCliente.getText());
        return new ClienteService().findById(id);
    }
    
    public JTextField getTxtIdCliente() {
        return txtIdCliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePicker = new raven.datetime.component.date.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("CODIGO");

        txtIdCliente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtIdClienteComponentShown(evt);
            }
        });
        txtIdCliente.addActionListener(this::txtIdClienteActionPerformed);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(txtIdCliente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .add(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtIdCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtIdClienteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtIdClienteComponentShown
        txtIdCliente.requestFocusInWindow();
        txtIdCliente.selectAll();
    }//GEN-LAST:event_txtIdClienteComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.datetime.component.date.DatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtIdCliente;
    // End of variables declaration//GEN-END:variables
}
