/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.imrob.appvendas;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
      
    }
}
