spring:
  application:
    name: vendas-server
  datasource:
    url: jdbc:postgresql://localhost:5432/db_vendas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    open-in-view: 'false'
  mvc:
    locale-resolver: fixed
    locale: pt_BR
