spring:
  application:
    name: vendas-server
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_vendas}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    open-in-view: 'false'
  mvc:
    locale-resolver: fixed
    locale: pt_BR
    format:
      date: dd-MM-yyyy
      date-time: dd-MM-yyyy HH:mm:ss
      time: HH:mm:ss
logging:
  level:
    org.springframework.jdbc.core: TRACE